### ISSUE TITLE
missing code to generate afd/flow

### ISSUE THREAD

**Issue by pritamqu** [f-ilic/AppearanceFreeActionRecognition#2]
In reference to [create-it-yourself](https://github.com/f-ilic/AppearanceFreeActionRecognition#create-it-yourself)
it seems that `generate_afd.py` and `generate_flow.py` codes are missing...
Could you please check? 

thanks a lot.

**Comment by f-ilic** [comment]
Hi,

At the top of your linked paragraph it says:
_Note: To run the following scripts `cd` into `afd/`_

Since the `afd/` directory is a git submodule be sure to clone the main repo properly with the `--recurse-submodules` flag, i.e.:
```git clone --recurse-submodules git@github.com:f-ilic/AppearanceFreeActionRecognition.git```

The files you mentioned are present here:
* [afd/generate_afd.py](https://github.com/f-ilic/afd/blob/290b859c1a838a9f9d3127cea0f89753107da05f/generate_afd.py)
* [afd/generate_flow.py](https://github.com/f-ilic/afd/blob/290b859c1a838a9f9d3127cea0f89753107da05f/generate_flow.py)


Does that help?

**Comment by pritamqu** [comment]
this is super helpful. thank you so much for such prompt response and wonderful work!
